"""empty message

Revision ID: 5a13546edc6c
Revises: 
Create Date: 2023-12-30 17:19:00.347172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a13546edc6c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_to_item_group',
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('item_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_group_id'], ['item_group.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_to_item_group')
    op.drop_table('item_group')
    op.drop_table('item')
    # ### end Alembic commands ###
